<form action="/users" method="post">
    <div>
    <label>
            Name
            <input type="text" name="user[name]">
        </label>
    </div>
    <div>
        <label>
            Email
            <input type="email" name="user[email]">
        </label>
    </div>
    <div>
        <label>
            Password
            <input type="password" name="user[password]">
        </label>
    </div>    <div>
        <label>
            Confirmation password
            <input type="password" name="user[passwordConfirmation]">
        </label>
    </div>
    <div>
        <label>
            City
            <select name="user[city]">
                <option value="3">Moscow</option>
                <option value="13">Penza</option>
                <option value="74">Chelyabinsk</option>
            </select>
        </label>
    </div>
    <input type="submit" value="Sign Up">
</form>
