<form action="/users" method="post">
    <div>
    <label>
            Name
            <input type="text" name="user[name]">
        </label>
        <?= ($errors['name']) ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" name="user[email]">
        </label>
        <?= ($errors['email']) ?>
    </div>
    <div>
        <label>
            Password
            <input type="password" name="user[password]">
        </label>
        <?= ($errors['password']) ?>
        <div>
            <label>
                Confirmation password
                <input type="password" name="user[passwordConfirmation]">
            </label>
            <p>
            <?= ($errors['passwordConfirmation']) ?>
            </p>
            <?= ($errors['passwordDoNotMatch']) ?>
        </div>
        
    </div>
    <div>
        <label>
            City
            <select name="user[city]">
                <option value="3">Moscow</option>
                <option value="13">Penza</option>
                <option value="74">Chelyabinsk</option>
            </select>
        </label>
    </div>
    <input type="submit" value="Sign Up">
</form>
