<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li> <?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
<?php endif; ?>
    </ul>
<!-- <?php var_dump($users) ?> -->
<form action='/users' nethod='get'>
    <input type="search" require name="find">
    <input type="submit" value="Search">
</form>
<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <a href="/users/<?= $user['id'] ?>"> <?= $user['name'] ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<form>
    <button>
        <a href="users/new">Add user</a>
    </button>
</form>